name: Update Other Repo

on:
  push:
    branches:
      - main  # Trigger when there's a push to the main branch

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "TMASC"
          git config --global user.email "tmasolutioncenter@gmail.com"
      
      - name: Checkout Target Repo
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.PAT_TOKEN }}@github.com/tma-solution-center/deploy.git
          cd deploy
          
          # Make your changes here
          sed -i '5s/.*/      tag: v4/' charts/fastapi/values.yaml
          
          # Commit and push the changes
          git add .
          git commit -m "Update from GitHub Actions"
          git push origin main
